# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#

[tools]
awscli = "latest"
hugo = "0.122.0"
python = "3.11.2"
task = "3.36.0"
trivy = "0.50.1"
