# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for REUSE:
#
# https://reuse.software/

version = 1
SPDX-PackageName = "sve-personal-website"
SPDX-PackageSupplier = "Stuart Ellis <https://www.stuartellis.name>"
SPDX-PackageDownloadLocation = "https://github.com/stuartellis/sve-personal-website"

[[annotations]]
path = "content/**/**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
